# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: Itinerancias
description: Itinerancias MNCARS
author:
  name: Juanjo
  email: juanjo.lopez@biko2.com

# Grunt handles images and assets.
source: app


# _config.build.yml sets future and show_drafts to false on `grunt build`
future: true
show_drafts: true

# Markdown library
markdown: kramdown
pygments: true
